export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';

export const UPDATED_PROFILE_REQUEST = 'UPDATED_PROFILE_REQUEST';
export const UPDATED_PROFILE_SUCCESS = 'UPDATED_PROFILE_SUCCESS';
export const UPDATED_PROFILE_RESET = 'UPDATED_PROFILE_RESET';
export const UPDATED_PROFILE_FAIL = 'UPDATED_PROFILE_FAIL';

export const UPDATED_PASSWORD_REQUEST = 'UPDATED_PASSWORD_REQUEST';
export const UPDATED_PASSWORD_SUCCESS = 'UPDATED_PASSWORD_SUCCESS';
export const UPDATED_PASSWORD_RESET = 'UPDATED_PASSWORD_RESET';
export const UPDATED_PASSWORD_FAIL = 'UPDATED_PASSWORD_FAIL';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
